### PR TITLE
Added CommitSetRollbackDuration action for Commit Confirmed extension

### PR DESCRIPTION
**Pull request by hellt**
This is an alternative version to #161.
In this version, a specific action is added to denote the Set Rollback Duration for the Commit Confirmed action.

### CODE REVIEW

**Comment by hellt** [comment]
@kidiyoor @dplore 
Hi gentlemen; I wonder how do we proceed with this one? 
I am fine with following the @kidiyoor suggestion and moving on with the separate action (which is the case expressed in this PR)

**Comment by hellt** [comment]
> LGTM. Please update https://github.com/openconfig/reference/blob/master/rpc/gnmi/gnmi-commit-confirmed.md as well.

Thanks @kidiyoor , raised https://github.com/openconfig/reference/pull/203 for this

**Comment by dplore** [comment]
This is a last call for comments.  This is planned to merge on Feb 15, 2024.

**Review by dplore — APPROVED** [review]

**Comment by hellt** [comment]
@dplore @kidiyoor with the recent commit I added generated stubs for Go and Py so that we can add this functionality to openconfig/gnmic client.

**Comment by hellt** [comment]
Hi @dplore
The planned merge date was on Feb 15. Is anything left that is gating this?

**Review by dplore — APPROVED** [review]

**Comment by dplore** [comment]
> Hi @dplore The planned merge date was on Feb 15. Is anything left that is gating this?

Thanks for the ping!

**Comment by robshakir** [comment]
This should have been merged upstream.

**Pull request merged**
